// Badge definitions - keep in sync with backend/src/db/badges.js
export const ALL_BADGES = [
  { key: 'first_wing',   emoji: '🍗', name: 'First Wing',    desc: 'Logged your first wings' },
  { key: 'ten_club',     emoji: '🔟', name: '10 Club',       desc: 'Eaten 10 wings total' },
  { key: 'century',      emoji: '💯', name: 'Century',       desc: 'Eaten 100 wings total' },
  { key: 'five_hundred', emoji: '🚀', name: '500 Club',      desc: 'Eaten 500 wings total' },
  { key: 'one_thousand', emoji: '👑', name: '1,000 Wings',   desc: 'Eaten 1,000 wings total' },
  { key: 'five_thousand',emoji: '🌟', name: '5,000 Wings',   desc: 'Eaten 5,000 wings total' },
  { key: 'big_session',  emoji: '💥', name: 'Big Session',   desc: 'Ate 20+ wings in one sitting' },
  { key: 'heavyweight',  emoji: '🏋️', name: 'Heavyweight',   desc: 'Ate 50+ wings in one sitting' },
  { key: 'glutton',      emoji: '👹', name: 'The Glutton',   desc: 'Ate 100+ wings in one sitting' },
  { key: 'food_blogger', emoji: '📸', name: 'Food Blogger',  desc: 'Attached a photo to a log' },
  { key: 'wing_tourist', emoji: '📍', name: 'Wing Tourist',  desc: 'Logged from 3 different locations' },
  { key: 'night_owl',    emoji: '🌙', name: 'Night Owl',     desc: 'Logged wings after midnight' },
  { key: 'early_bird',   emoji: '🌅', name: 'Early Bird',    desc: 'Logged wings before 9am' },
  { key: 'number_one',   emoji: '🏆', name: '#1',            desc: 'Held the top leaderboard spot' },
  { key: 'camera_shy',   emoji: '🙈', name: 'Camera Shy',    desc: 'Logged wings 5 times without a photo' },
  { key: 'birthday',     emoji: '🎂', name: 'Birthday Wings', desc: 'Logged wings on your birthday' },
  { key: 'thanksgiving', emoji: '🦃', name: 'Thanksgiving',  desc: 'Logged wings on Thanksgiving' },
  { key: 'christmas',    emoji: '🎄', name: 'Christmas',     desc: 'Logged wings on Christmas' },
  { key: 'new_years',    emoji: '🎆', name: "New Year's",    desc: "Logged wings on New Year's Day" },
  { key: 'new_years_eve',emoji: '🥂', name: "New Year's Eve",desc: "Logged wings on New Year's Eve" },
  { key: 'fourth_of_july',emoji: '🎇',name: '4th of July',  desc: 'Logged wings on the 4th of July' },
  { key: 'halloween',    emoji: '🎃', name: 'Halloween',     desc: 'Logged wings on Halloween' },
  { key: 'super_bowl',   emoji: '🏈', name: 'Super Bowl',    desc: 'Logged wings on Super Bowl Sunday' },
  { key: 'valentines',   emoji: '❤️',  name: "Valentine's",  desc: "Logged wings on Valentine's Day" },
  { key: 'st_patricks',  emoji: '🍀', name: "St. Patrick's", desc: "Logged wings on St. Patrick's Day" },
  { key: 'cinco_de_mayo',emoji: '🌮', name: 'Cinco de Mayo', desc: 'Logged wings on Cinco de Mayo' },
  { key: 'arbor_day',    emoji: '🌳', name: 'Arbor Day',     desc: 'Logged wings on Arbor Day' },
  { key: 'mlk_day',      emoji: '✊', name: 'MLK Day',       desc: 'Logged wings on MLK Jr. Day' },
];
